spring.application.name=foodmap
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3308/foodmap?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# Swagger UI ??
springdoc.swagger-ui.path=/swagger

# Kakao REST API
kakao.api.base-url=https://dapi.kakao.com
kakao.api.key=${KAKAO_REST_API_KEY}
kakao.api.timeout-ms=3000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=
spring.data.redis.timeout=3s

# ?? TTL
# 60? (?? ??/?? ??)
cache.ttl.search.seconds=3600
# 30? (?????)
cache.ttl.geocode.seconds=2592000

spring.batch.jdbc.initialize-schema=always
